/* New student registration workflow */
(function(){
  const ready=()=>window.supabase&&window.SUPABASE_URL&&window.SUPABASE_PUBLISHABLE_KEY;
  let client=null;
  function db(){if(!client){if(!ready())throw new Error('Supabase configuration is not ready.');client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);}return client;}
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function ensureModal(){
    let m=document.getElementById('registrationModal'); if(m)return m;
    m=document.createElement('div');m.id='registrationModal';m.className='registration-modal hidden';m.innerHTML=`<div class="registration-backdrop" data-close-registration></div><div class="registration-card"><div class="registration-header"><div><div class="eyebrow">BANTING SCRABBLE ACADEMY</div><h2 id="registrationTitle">Register New Student</h2><p id="registrationSubtitle" class="subtle">Choose how you want to register.</p></div><button class="modal-close" type="button" data-close-registration aria-label="Close">×</button></div><div id="registrationBody"></div></div>`;
    document.body.appendChild(m);m.querySelectorAll('[data-close-registration]').forEach(x=>x.addEventListener('click',close));return m;
  }
  function close(){document.getElementById('registrationModal')?.classList.add('hidden');}
  function open(){const m=ensureModal();document.getElementById('registrationTitle').textContent='Register New Student';document.getElementById('registrationSubtitle').textContent='Choose how you want to register.';document.getElementById('registrationBody').innerHTML=`<div class="registration-choice-grid"><button type="button" class="registration-choice" id="regNew"><span class="registration-choice-icon">+</span><strong>New Parent</strong><small>I do not have a Parent Portal account.</small></button><button type="button" class="registration-choice" id="regExisting"><span class="registration-choice-icon">↗</span><strong>Existing Parent</strong><small>I already have a Parent Portal account.</small></button></div>`;m.classList.remove('hidden');document.getElementById('regNew').onclick=()=>newParent();document.getElementById('regExisting').onclick=()=>existingParent();}
  function newParent(){const m=ensureModal();document.getElementById('registrationTitle').textContent='New Parent Registration';document.getElementById('registrationSubtitle').textContent='Create your Parent Portal account and register your student.';document.getElementById('registrationBody').innerHTML=`<form id="newParentForm" class="registration-form"><div class="registration-form-section"><div class="eyebrow">01 · PARENT ACCOUNT</div><div class="formgrid"><div><label>Parent / Guardian Name <em>*</em></label><input id="regParentName" required></div><div><label>Email <em>*</em></label><input id="regParentEmail" type="email" required></div></div><div class="formgrid"><div><label>WhatsApp Number</label><input id="regWhatsApp"></div><div><label>Emergency Contact</label><input id="regEmergency"></div></div><div class="formgrid"><div><label>Create Password <em>*</em></label><input id="regPassword" type="password" autocomplete="new-password" required></div><div><label>Confirm Password <em>*</em></label><input id="regPassword2" type="password" autocomplete="new-password" required></div></div><div class="subtle">At least 8 characters with uppercase, lowercase and a number.</div></div><div class="registration-form-section"><div class="eyebrow">02 · STUDENT</div><div class="formgrid"><div><label>Student Name <em>*</em></label><input id="regStudentName" required></div><div><label>School</label><input id="regSchool"></div></div><div class="formgrid"><div><label>Age</label><input id="regAge" type="number" min="1" max="18"></div><div><label>Scrabble Experience</label><select id="regExperience"><option value="">Choose experience</option><option>Never played before</option><option>Beginner.</option><option>Intermediate.</option></select></div></div><div><label>Preferred Class <em>*</em></label><select id="regClass" required><option value="">Choose class</option><option>10:30 AM</option><option>2:00 PM</option></select></div></div><label class="commitment-check"><input id="regDeclaration" type="checkbox" required><span>I confirm the information provided is correct and agree to teacher review.</span></label><div id="registrationMessage" class="subtle"></div><div class="form-actions"><button type="button" class="secondary" id="regBack">Back</button><button type="submit" class="primary">Submit Registration</button></div></form>`;document.getElementById('regBack').onclick=open;document.getElementById('newParentForm').onsubmit=submitNew;}
  async function existingParent(){const c=db();const{data}=await c.auth.getUser();if(!data.user){close();if(typeof window.setLoginMode==='function')window.setLoginMode('parent');alert('Please sign in to your Parent account first. Then choose Register New Student inside the Parent Portal.');return;}const{data:a,error}=await c.from('parent_accounts').select('user_id,parent_name,email,whatsapp,active').eq('user_id',data.user.id).maybeSingle();if(error)throw error;if(!a||a.active===false){alert('Please sign in with an active Parent account.');return;}showExisting(a);}
  function showExisting(a){const m=ensureModal();document.getElementById('registrationTitle').textContent='Add New Student';document.getElementById('registrationSubtitle').textContent='Your existing Parent account will stay linked to all children.';document.getElementById('registrationBody').innerHTML=`<form id="existingParentForm" class="registration-form"><div class="registration-form-section"><div class="eyebrow">NEW STUDENT</div><div class="formgrid"><div><label>Student Name <em>*</em></label><input id="regStudentName" required></div><div><label>School</label><input id="regSchool"></div></div><div class="formgrid"><div><label>Age</label><input id="regAge" type="number" min="1" max="18"></div><div><label>Scrabble Experience</label><select id="regExperience"><option value="">Choose experience</option><option>Never played before</option><option>Beginner.</option><option>Intermediate.</option></select></div></div><div><label>Preferred Class <em>*</em></label><select id="regClass" required><option value="">Choose class</option><option>10:30 AM</option><option>2:00 PM</option></select></div></div><label class="commitment-check"><input id="regDeclaration" type="checkbox" required><span>I confirm the information provided is correct and agree to teacher review.</span></label><div id="registrationMessage" class="subtle"></div><div class="form-actions"><button type="button" class="secondary" id="regBack">Cancel</button><button type="submit" class="primary">Submit Registration</button></div></form>`;m.classList.remove('hidden');document.getElementById('regBack').onclick=close;document.getElementById('existingParentForm').onsubmit=e=>submitExisting(e,a);}
  async function invoke(body){const{data,error}=await db().functions.invoke('submit-student-registration',{body});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Unable to submit registration.');return data;}
  function valid(p){return p.length>=8&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/[0-9]/.test(p);}
  async function submitNew(e){e.preventDefault();const msg=document.getElementById('registrationMessage'),p=document.getElementById('regPassword').value,p2=document.getElementById('regPassword2').value;if(!valid(p)){msg.textContent='Use at least 8 characters with uppercase, lowercase and a number.';return}if(p!==p2){msg.textContent='The passwords do not match.';return}msg.textContent='Submitting registration...';try{const d=await invoke({registration_type:'new_parent',parent_name:regParentName.value.trim(),parent_email:regParentEmail.value.trim(),parent_whatsapp:regWhatsApp.value.trim(),emergency_contact:regEmergency.value.trim(),student_name:regStudentName.value.trim(),school:regSchool.value.trim(),age:regAge.value||null,scrabble_experience:regExperience.value,preferred_class_time:regClass.value,password:p});document.getElementById('registrationTitle').textContent='Registration Submitted';document.getElementById('registrationSubtitle').textContent='Pending teacher review';document.getElementById('registrationBody').innerHTML=`<div class="registration-success"><div class="registration-success-icon">✓</div><h3>Registration received</h3><p>Your registration is waiting for teacher approval.</p><p class="subtle">Registration ID: ${esc(d.registration_id)}</p><button type="button" class="primary" id="regDone">Done</button></div>`;document.getElementById('regDone').onclick=close;}catch(err){msg.textContent=err.message||'Unable to submit registration.';}}
  async function submitExisting(e,a){e.preventDefault();const msg=document.getElementById('registrationMessage');msg.textContent='Submitting registration...';try{await invoke({registration_type:'existing_parent',parent_name:a.parent_name,parent_email:a.email,parent_whatsapp:a.whatsapp||'',student_name:regStudentName.value.trim(),school:regSchool.value.trim(),age:regAge.value||null,scrabble_experience:regExperience.value,preferred_class_time:regClass.value});close();alert('Registration submitted. The teacher will review the new student.');}catch(err){msg.textContent=err.message||'Unable to submit registration.';}}
  async function loadTeacher(){const nav=[...document.querySelectorAll('.side .nav')].find(x=>x.id==='teacherRegistrationEntry');document.querySelectorAll('.side .nav').forEach(x=>x.classList.remove('active'));nav?.classList.add('active');const c=db();const{data:u}=await c.auth.getUser();if(!u.user){alert('Please sign in first.');return}const{data:a}=await c.from('parent_accounts').select('user_id').eq('user_id',u.user.id).maybeSingle();if(a){alert('Parent accounts cannot review registrations.');return}let page=document.getElementById('registrationReviewPage');if(!page){page=document.createElement('section');page.id='registrationReviewPage';page.className='registration-review-page';page.innerHTML=`<div class="page-intro"><div><div class="eyebrow">REGISTRATION REVIEW</div><h2>New Registrations</h2><p>Review new student applications before adding them to the active class records.</p></div><button class="secondary" id="regRefresh">Refresh</button></div><div class="registration-filter"><button class="secondary active" data-status="Pending Review">Pending Review</button><button class="secondary" data-status="Approved">Approved</button><button class="secondary" data-status="Rejected">Rejected</button></div><div id="registrationReviewList"></div>`;document.querySelector('.main')?.appendChild(page);page.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>renderTeacher(b.dataset.status));document.getElementById('regRefresh').onclick=()=>renderTeacher('Pending Review');}document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));page.classList.add('active');document.getElementById('title').textContent='New Registrations';await renderTeacher('Pending Review');}
  async function renderTeacher(status){const box=document.getElementById('registrationReviewList');if(!box)return;box.innerHTML='<div class="panel"><div class="empty">Loading registrations...</div></div>';const{data,error}=await db().from('student_registrations').select('*').eq('status',status).order('submitted_at',{ascending:false});if(error){box.innerHTML=`<div class="panel"><div class="empty">${esc(error.message)}</div></div>`;return}if(!data?.length){box.innerHTML='<div class="panel"><div class="empty">No registrations in this section.</div></div>';return}box.innerHTML=data.map(r=>`<div class="registration-review-card"><div class="registration-card-top"><div><div class="eyebrow">${esc(r.registration_type==='new_parent'?'NEW PARENT':'EXISTING PARENT')}</div><h3>${esc(r.student_name)}</h3><p class="subtle">${esc(r.parent_name)} · ${esc(r.parent_email)}</p></div><span class="badge blue">REG ${esc(r.registration_id)}</span></div><div class="registration-grid"><div><small>School</small><strong>${esc(r.school||'Not provided')}</strong></div><div><small>Age</small><strong>${esc(r.age||'Not provided')}</strong></div><div><small>Experience</small><strong>${esc(r.scrabble_experience||'Not provided')}</strong></div><div><small>Preferred Class</small><strong>${esc(r.preferred_class_time)}</strong></div><div><small>WhatsApp</small><strong>${esc(r.parent_whatsapp||'Not provided')}</strong></div><div><small>Submitted</small><strong>${esc(new Date(r.submitted_at).toLocaleString())}</strong></div></div>${r.rejection_reason?`<div class="registration-reason"><b>Reason:</b> ${esc(r.rejection_reason)}</div>`:''}<div class="registration-card-bottom">${status==='Pending Review'?`<div class="registration-actions"><button class="primary" data-approve="${r.registration_id}">Approve</button><button class="secondary danger-button" data-reject="${r.registration_id}">Reject</button></div>`:`<span class="badge ${status==='Approved'?'paid':'absent'}">${esc(status)}</span>`}</div></div>`).join('');box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>review(Number(b.dataset.approve),'approve'));box.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>review(Number(b.dataset.reject),'reject'));}
  async function review(id,action){let reason='';if(action==='reject'){reason=prompt('Enter the reason for rejection:')?.trim()||'';if(!reason)return}else if(!confirm('Approve this registration? A Student ID will be generated.'))return;try{const{data,error}=await db().functions.invoke('review-student-registration',{body:{registration_id:id,action,rejection_reason:reason}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Unable to process registration.');await renderTeacher(action==='approve'?'Pending Review':'Pending Review');alert(action==='approve'?`Registration approved. Student ID: ${data.student_id}`:'Registration rejected.');}catch(e){alert(e.message||'Unable to process registration.');}}
  function inject(){
    if(!document.getElementById('registerNewStudentEntry')){const b=document.createElement('button');b.type='button';b.id='registerNewStudentEntry';b.className='secondary register-new-student-button';b.textContent='Register New Student';b.onclick=open;const form=document.querySelector('#loginScreen .form');if(form)form.appendChild(b);}
    if(!document.getElementById('teacherRegistrationEntry')){const b=document.createElement('button');b.type='button';b.id='teacherRegistrationEntry';b.className='nav';b.innerHTML='<span class="nav-icon">06</span><span>New Registrations</span>';b.onclick=loadTeacher;const orders=[...document.querySelectorAll('.side .nav')].find(x=>x.textContent.includes('Orders'));orders?.after(b);}const reports=[...document.querySelectorAll('.side .nav')].find(x=>x.querySelector('.nav-icon + span')?.textContent.trim().toLowerCase()==='reports');if(reports){const icon=reports.querySelector('.nav-icon');if(icon)icon.textContent='07';}
    if(!document.getElementById('parentRegistrationEntry')){const b=document.createElement('button');b.type='button';b.className='primary parent-register-student-button';b.id='parentRegistrationEntry';b.textContent='+ Register New Student';b.onclick=open;const p=document.querySelector('.parent-portal .parent-shell');if(p){const card=p.querySelector('.parent-card');card?.appendChild(b);}}
  }
  window.openRegistrationChoice=open;window.closeRegistrationModal=close;window.openTeacherRegistrations=loadTeacher;
  document.addEventListener('DOMContentLoaded',()=>{inject();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});});
})();
