/* SCMS Teacher Attendance UI and workflow module */
/* ===== ATTENDANCE ===== */
function renderHome(){const date=selectedAttendanceDate();document.getElementById('today').textContent=formatDateClient(date);const students=activeStudents().filter(s=>registrationDateKey(s['Registration Date'])<=date);const attendance=attendanceForDate(date);const byId=new Map(students.map(s=>[String(s['Student ID']),s]));const absentById=new Map();['10:30 AM','2:00 PM'].forEach(time=>{const id=time==='10:30 AM'?'1030':'1400';const panelStudents=students.filter(s=>String(s['Normal Class Time'])===time);const records=new Map(attendance.filter(a=>byId.has(String(a['Student ID']))).map(a=>[String(a['Student ID']),a]));let present=0,other=0,absent=0;panelStudents.forEach(s=>{const a=records.get(String(s['Student ID']));if(!a)return;if(a.Status==='Absent'){absent++;absentById.set(String(s['Student ID']),s);return}if(a.Status==='Present'){if(String(a['Actual Class Time'])===time)present++;else other++}});document.getElementById('c'+id).textContent=panelStudents.length+' students';document.getElementById('p'+id).textContent=present;document.getElementById('a'+id).textContent=absent;document.getElementById('o'+id).textContent=other});attendance.forEach(a=>{if(a.Status==='Absent'){const s=byId.get(String(a['Student ID']));if(s)absentById.set(String(a['Student ID']),s)}});const absentStudents=[...absentById.values()].sort((a,b)=>String(a['Student Name']).localeCompare(String(b['Student Name'])));document.getElementById('homeAbsentCount').textContent=absentStudents.length;document.getElementById('homeAbsentStudents').innerHTML=absentStudents.map(s=>studentButton(s['Student ID'],s['Student Name'],'absent-attendance')).join('')||'<div class="empty">No absent students.</div>';const cycles=students.map(s=>cycleFor(s['Student ID']));const activeOrders=DATA.orders.filter(o=>String(o.Archived||'').toLowerCase()!=='yes');const pendingOrders=activeOrders.filter(o=>['Pending Order','Pending Payment'].includes(String(o['Order Status']||''))).length;const unpaidOrders=activeOrders.filter(o=>String(o['Payment Status']||'').toLowerCase()==='unpaid').length;const actionBox=document.getElementById('homeActionRequired');if(actionBox){const due=cycles.filter(x=>x>=4).length;const items=[];if(due)items.push(`<button class="action-item" onclick="page('payments')"><span><b>${due}</b> package payment${due===1?'':'s'} due</span><span>›</span></button>`);if(pendingOrders)items.push(`<button class="action-item" onclick="page('orders')"><span><b>${pendingOrders}</b> order${pendingOrders===1?'':'s'} need attention</span><span>›</span></button>`);if(unpaidOrders&&unpaidOrders!==pendingOrders)items.push(`<button class="action-item" onclick="page('orders')"><span><b>${unpaidOrders}</b> unpaid order${unpaidOrders===1?'':'s'}</span><span>›</span></button>`);actionBox.innerHTML=items.length?items.join(''):'<div class="action-ok-row"><span>Everything is up to date</span></div>';}}
	function setHomeDate(delta){let d=new Date(selectedAttendanceDate()+'T12:00:00');if(delta===0)d=latestSunday();else d.setDate(d.getDate()+delta);if(d.getDay()!==0)d=latestSunday(d);document.getElementById('attDate').value=isoDate(d);renderHome()}
function setAttDate(delta){let d=new Date(selectedAttendanceDate()+'T12:00:00');if(delta===0)d=latestSunday();else d.setDate(d.getDate()+delta);if(d.getDay()!==0)d=latestSunday(d);document.getElementById('attDate').value=isoDate(d);renderAttendance();renderHome()}
function openAttendance(time){page('attendance');document.getElementById('attDate').value=isoDate(latestSunday());renderAttendance()}
function renderAttendance(){const date=selectedAttendanceDate();document.getElementById('attDate').value=date;const students=activeStudents().filter(s=>registrationDateKey(s['Registration Date'])<=date).sort((a,b)=>{const ta=a['Normal Class Time']||'99';const tb=b['Normal Class Time']||'99';return ta.localeCompare(tb)||String(a['Student Name']).localeCompare(String(b['Student Name']))});const marked=students.filter(s=>DATA.attendance.some(a=>String(a['Student ID'])===String(s['Student ID'])&&String(a.Date).slice(0,10)===date)).length;document.getElementById('attSummary').textContent=marked+' / '+students.length+' marked';document.getElementById('attContent').innerHTML=`<div class="panel"><div class="scroll"><table><thead><tr><th>Student</th><th>Normal Class</th><th>Actual Class</th><th>Status</th><th>Attendance</th></tr></thead><tbody>${students.map(s=>attendanceRow(s,date)).join('')||'<tr><td colspan="5" class="empty">No active students registered.</td></tr>'}</tbody></table></div></div>`}
function viewAttendanceList(time){page('attendance');document.getElementById('attDate').value=selectedAttendanceDate();renderAttendance()}
function attendanceRow(s,date){const a=DATA.attendance.find(x=>String(x['Student ID'])===String(s['Student ID'])&&attendanceDateKey(x.Date)===date);const status=a?.Status||'Not marked';const time=a?.['Actual Class Time']||'';return `<tr><td><button class="linkbtn" onclick="openStudent('${esc(s['Student ID'])}')">${esc(s['Student Name'])}</button><div class="subtle">${esc(s['Student ID'])}</div></td><td>${esc(s['Normal Class Time']||'')}</td><td>${esc(time||'-')}</td><td>${status==='Present'?'<span class="badge present">Present</span>':status==='Absent'?'<span class="badge absent">Absent</span>':'<span class="badge neutral">Not marked</span>'}</td><td><div class="att-actions"><button class="att-btn ${status==='Present'&&time==='10:30 AM'?'selected':''}" onclick="setAttendance('${esc(s['Student ID'])}','${date}','10:30 AM','Present')">10:30 AM</button><button class="att-btn ${status==='Present'&&time==='2:00 PM'?'selected':''}" onclick="setAttendance('${esc(s['Student ID'])}','${date}','2:00 PM','Present')">2:00 PM</button><button class="att-btn absent ${status==='Absent'?'selected':''}" onclick="setAttendance('${esc(s['Student ID'])}','${date}','', 'Absent')">Absent</button><button class="att-btn" onclick="resetAttendanceAction('${esc(s['Student ID'])}','${date}')">Reset</button></div></td></tr>`}
async function setAttendance(studentId,date,classTime,status){const existing=DATA.attendance.find(a=>String(a['Student ID'])===String(studentId)&&attendanceDateKey(a.Date)===date);try{await run('saveAttendance',{attendanceId:existing?.['Attendance ID']||'',studentId,date,classTime,status,notes:''});DATA=await run('getData');renderAll()}catch(e){appNotify(e.message||e)}}
async function resetAttendanceAction(studentId,date){try{DATA=await run('resetAttendance',studentId,date);renderAll()}catch(e){appNotify(e.message||e)}}
function setStudentView(view){studentView=view;document.getElementById('activeStudentsBtn')?.classList.toggle('active',view==='active');document.getElementById('archivedStudentsBtn')?.classList.toggle('active',view==='archived');renderStudents()}
function closeStudentActionMenus(){document.querySelectorAll('.student-action-menu.show').forEach(m=>m.classList.remove('show'))}
function toggleStudentActionMenu(event,id){
  event.stopPropagation();
  const menu=document.getElementById('studentActionMenu-'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_'));
  if(!menu)return;
  const wasOpen=menu.classList.contains('show');
  closeStudentActionMenus();
  if(!wasOpen)menu.classList.add('show');
}
function runStudentAction(event,fn,id){event.stopPropagation();closeStudentActionMenus();fn(id)}
document.addEventListener('click',event=>{if(!event.target.closest('.student-action-wrap'))closeStudentActionMenus()});
