-- Billplz payment request tracking and idempotency
-- Run once in Supabase SQL Editor before deploying the updated functions.

create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  request_key text not null unique,
  bill_id text unique,
  bill_url text,
  student_id text not null references public.students(student_id) on delete cascade,
  cycle_number integer not null,
  amount numeric not null default 50,
  status text not null default 'Pending'
    check (status in ('Pending','Paid','Failed','Cancelled')),
  transaction_id text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists payment_requests_student_idx
  on public.payment_requests(student_id);

create index if not exists payment_requests_status_idx
  on public.payment_requests(status);

create or replace function public.set_payment_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists payment_requests_updated_at on public.payment_requests;
create trigger payment_requests_updated_at
before update on public.payment_requests
for each row execute function public.set_payment_requests_updated_at();

alter table public.payment_requests enable row level security;

-- Remove any previous policies with these names so the script is safe to rerun.
drop policy if exists "payment_requests_teacher_select" on public.payment_requests;
drop policy if exists "payment_requests_teacher_update" on public.payment_requests;

create policy "payment_requests_teacher_select"
on public.payment_requests
for select
using (public.is_teacher());

create policy "payment_requests_teacher_update"
on public.payment_requests
for update
using (public.is_teacher())
with check (public.is_teacher());

-- Parents intentionally receive no direct policy on this table.
-- Edge Functions use the Supabase secret key for controlled server-side access.
