/* SCMS certificate generation service */
(function(){
  'use strict';
  const renderer=window.SCMSCertificateRenderer,storage=window.SCMSCertificateStorage,rules=window.SCMSCertificateRules;
  function notify(message,type,title,options){if(typeof appNotify==='function')appNotify(message,type||'info',title||'',options||{});else console.warn(message)}
  async function canvasToBlob(canvas,type,quality){return new Promise(function(resolve,reject){canvas.toBlob(function(blob){blob?resolve(blob):reject(new Error('Unable to create certificate image.'))},type,quality)})}
  async function preview(tournament,award){if(!award||!award.student_id)throw new Error('No student is linked to this award.');await renderer.ensureAssets();const certificateNo=award.certificate_number||rules.certificateNumber(tournament,award);const workingAward=Object.assign({},award,{title:award.title||award.award_type,certificate_number:certificateNo,certificate_caption:award.certificate_caption||rules.awardCaption(award.award_type,tournament.name)});const canvas=renderer.drawCertificate(tournament,workingAward);return {imageData:canvas.toDataURL('image/jpeg',0.94),certificateNumber:certificateNo}}
  async function generateOne(tournament,award){if(!award||!award.student_id)return {skipped:true,reason:'No student linked'};await renderer.ensureAssets();const certificateNo=award.certificate_number||rules.certificateNumber(tournament,award);const caption=award.certificate_caption||rules.awardCaption(award.award_type,tournament.name);const workingAward=Object.assign({},award,{title:award.title||award.award_type,certificate_number:certificateNo,certificate_caption:caption});const canvas=renderer.drawCertificate(tournament,workingAward);if(!window.jspdf||!window.jspdf.jsPDF)throw new Error('PDF engine is unavailable. Refresh the page and try again.');const PDF=window.jspdf.jsPDF;const pdf=new PDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',0.94),'JPEG',0,0,297,210,undefined,'FAST');const pdfBlob=pdf.output('blob');const thumbnailCanvas=document.createElement('canvas');thumbnailCanvas.width=600;thumbnailCanvas.height=Math.round(600*renderer.CONFIG.templateHeight/renderer.CONFIG.templateWidth);thumbnailCanvas.getContext('2d').drawImage(canvas,0,0,thumbnailCanvas.width,thumbnailCanvas.height);const thumbnailBlob=await canvasToBlob(thumbnailCanvas,'image/jpeg',0.88);const base='certificates/'+storage.safePath(tournament.tournament_id)+'/'+storage.safePath(award.student_id)+'-'+storage.safePath(rules.awardCode(award.award_type));const pdfPath=base+'.pdf',thumbnailPath=base+'.jpg';await storage.upload(pdfPath,pdfBlob,'application/pdf');await storage.upload(thumbnailPath,thumbnailBlob,'image/jpeg');const awardUpdate={certificate_path:pdfPath,certificate_number:certificateNo,certificate_status:'published',certificate_caption:caption,certificate_generated_at:new Date().toISOString()};const awardResult=await supabaseClient.from('tournament_awards').update(awardUpdate).eq('award_id',award.award_id);if(awardResult.error)throw awardResult.error;const achievement=await storage.upsertAchievement(tournament,workingAward,pdfPath,thumbnailPath);if(achievement?.achievement_id){const linkResult=await supabaseClient.from('tournament_awards').update({achievement_id:achievement.achievement_id}).eq('award_id',award.award_id);if(linkResult.error)throw linkResult.error}return {certificateNo:certificateNo,pdfPath:pdfPath,thumbnailPath:thumbnailPath,achievementId:achievement?.achievement_id||null}}
  async function generateForAwards(tournament,awards){const list=(awards||[]).filter(function(a){return a&&a.student_id});if(!list.length)return {generated:0,failed:0};let generated=0,failed=0;for(const award of list){try{await generateOne(tournament,award);generated++}catch(error){failed++;await supabaseClient.from('tournament_awards').update({certificate_status:'failed'}).eq('award_id',award.award_id);console.error('Certificate generation failed:',error)}}return {generated:generated,failed:failed}}
  async function generateTournament(tournament,awards){try{const result=await generateForAwards(tournament,awards);if(result.generated)notify(result.generated+' certificate'+(result.generated===1?'':'s')+' generated and linked to Parent Portal.','success','Certificates Generated',{variant:'registration'});if(result.failed)notify(result.failed+' certificate'+(result.failed===1?'':'s')+' failed. Open the tournament and retry generation.','error','Certificate Generation Incomplete',{variant:'critical'});return result}catch(error){notify(error.message||String(error),'error','Certificates Not Generated',{variant:'critical'});return {generated:0,failed:awards?.length||0}}}
  async function retryFailed(tournamentId){const result=await supabaseClient.from('tournament_awards').select('*').eq('tournament_id',tournamentId).eq('certificate_status','failed');if(result.error)throw result.error;const tournamentResult=await supabaseClient.from('tournaments').select('*').eq('tournament_id',tournamentId).single();if(tournamentResult.error)throw tournamentResult.error;return generateTournament(tournamentResult.data,result.data||[])}
  window.SCMSCertificateGenerator={preview:preview,generateForAwards:generateForAwards,generateTournament:generateTournament,retryFailed:retryFailed};
})();
