/* SCMS certificate renderer
 * Browser-only rendering. No Supabase or PDF storage logic.
 */
(function(){
  'use strict';
  const CONFIG=Object.freeze({templatePath:'assets/certificate-template.png',signaturePath:'assets/certificate-signature.png',templateWidth:1492,templateHeight:1054});
  let templateImage=null,signatureImage=null;
  function loadImage(path){return new Promise(function(resolve,reject){const image=new Image();image.onload=function(){resolve(image)};image.onerror=function(){reject(new Error('Certificate asset could not be loaded: '+path))};image.src=path+'?v=20261005.1';})}
  async function ensureAssets(){if(!templateImage)templateImage=await loadImage(CONFIG.templatePath);if(!signatureImage){try{signatureImage=await loadImage(CONFIG.signaturePath)}catch(e){signatureImage=null}}}
  function fitFont(ctx,text,maxWidth,startSize,family,weight){let size=startSize;ctx.font=(weight||'700')+' '+size+'px '+family;while(size>18&&ctx.measureText(text).width>maxWidth){size-=1;ctx.font=(weight||'700')+' '+size+'px '+family}return size}
  function drawCentered(ctx,text,x,y,maxWidth,size,color,family,weight){const fontFamily=family||'Georgia, Times New Roman, serif';const fontWeight=weight||'700';const actual=fitFont(ctx,text,maxWidth,size,fontFamily,fontWeight);ctx.font=fontWeight+' '+actual+'px '+fontFamily;ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y)}
  function transparentSignatureSource(image){const c=document.createElement('canvas');c.width=image.naturalWidth||image.width;c.height=image.naturalHeight||image.height;const x=c.getContext('2d');x.drawImage(image,0,0);const data=x.getImageData(0,0,c.width,c.height);for(let i=0;i<data.data.length;i+=4){const r=data.data[i],g=data.data[i+1],b=data.data[i+2];if(r>242&&g>242&&b>242)data.data[i+3]=0}x.putImageData(data,0,0);return c}
  function drawSignature(ctx){if(!signatureImage)return;try{const source=transparentSignatureSource(signatureImage);const maxW=250,maxH=72;const ratio=Math.min(maxW/source.width,maxH/source.height);const w=source.width*ratio,h=source.height*ratio;ctx.drawImage(source,746-w/2,910-h/2,w,h)}catch(e){console.warn('Certificate signature overlay failed:',e)}}
  function drawCertificate(tournament,award){const canvas=document.createElement('canvas');canvas.width=CONFIG.templateWidth;canvas.height=CONFIG.templateHeight;const ctx=canvas.getContext('2d');ctx.drawImage(templateImage,0,0,canvas.width,canvas.height);const navy='#10264f';const studentName=String(award.student_name||'');const title=String(award.title||award.award_type||'Achievement');const eventName=String(tournament.name||'Scrabble Tournament');const eventDate=String(tournament.event_date||'').slice(0,10);const certificateNo=String(award.certificate_number||window.SCMSCertificateRules.certificateNumber(tournament,award));drawCentered(ctx,studentName,746,482,800,38,navy,'Georgia, Times New Roman, serif','700');drawCentered(ctx,title,746,598,700,(String(award.award_type||title).match(/^(1st|2nd|3rd) Place$/i)?58:44),'#f8d27a','Georgia, Times New Roman, serif','700');drawCentered(ctx,eventName,746,690,520,24,navy,'Georgia, Times New Roman, serif','700');drawCentered(ctx,eventDate?new Date(eventDate+'T12:00:00').toLocaleDateString(undefined,{day:'2-digit',month:'long',year:'numeric'}):'',746,731,520,22,navy,'Georgia, Times New Roman, serif','600');drawSignature(ctx);drawCentered(ctx,certificateNo,1255,976,250,13,navy,'Arial, Helvetica, sans-serif','600');return canvas}
  window.SCMSCertificateRenderer={CONFIG:CONFIG,ensureAssets:ensureAssets,drawCertificate:drawCertificate};
})();
