import { createClient } from "npm:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
function keys(){const pub=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default;const secret=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default;if(!pub||!secret)throw new Error("Supabase server configuration is incomplete.");return{pub,secret};}
async function sendMail(to:string,subject:string,html:string){const apiKey=Deno.env.get("RESEND_API_KEY");if(!apiKey)return;const from=Deno.env.get("PAYMENT_NOTIFICATION_FROM")||"onboarding@resend.dev";const res=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,html})});if(!res.ok)console.error("Registration email failed",await res.text());}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders}); if(req.method!=="POST")return json({error:"Method not allowed."},405);
 try{const{pub,secret}=keys();const url=Deno.env.get("SUPABASE_URL")!;const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"Teacher authentication required."},401);const caller=createClient(url,pub,{global:{headers:{Authorization:auth}}});const{data:u,error:ue}=await caller.auth.getUser();if(ue||!u.user)return json({error:"Your teacher session has expired."},401);const admin=createClient(url,secret);const{data:parent}=await admin.from("parent_accounts").select("user_id").eq("user_id",u.user.id).maybeSingle();if(parent)return json({error:"Parent accounts cannot review registrations."},403);
 const body=await req.json();const id=Number(body.registration_id);const action=body.action==="reject"?"reject":"approve";const reason=String(body.rejection_reason||"").trim();if(!Number.isInteger(id)||id<1)return json({error:"Registration ID is required."},400);const{data:r,error:re}=await admin.from("student_registrations").select("*").eq("registration_id",id).maybeSingle();if(re)throw re;if(!r)return json({error:"Registration not found."},404);if(r.status!=="Pending Review")return json({error:"This registration has already been processed."},409);
 if(action==="reject"){if(!reason)return json({error:"Enter a rejection reason."},400);const{error}=await admin.from("student_registrations").update({status:"Rejected",rejection_reason:reason,reviewed_at:new Date().toISOString(),reviewed_by:u.user.id}).eq("registration_id",id).eq("status","Pending Review");if(error)throw error;await sendMail(r.parent_email,"Banting Scrabble Academy Registration Update",`<div style="font-family:Arial,sans-serif"><h2>Registration Update</h2><p>Dear ${r.parent_name},</p><p>The registration for <strong>${r.student_name}</strong> was not approved.</p><p>Reason: <strong>${reason}</strong></p></div>`);return json({success:true,status:"Rejected"});}
 const{data:existing}=await admin.from("students").select("student_id").ilike("student_name",r.student_name).eq("email",r.parent_email).limit(1).maybeSingle();if(existing)return json({error:"A matching student record already exists."},409);const{data:sid,error:sidError}=await admin.rpc("next_student_id_for_registration");if(sidError)throw sidError;const studentId=String(sid);const{error:studentError}=await admin.from("students").insert({student_id:studentId,student_name:r.student_name,school:r.school||"",age:r.age,scrabble_experience:r.scrabble_experience||"",parent_guardian:r.parent_name,whatsapp:r.parent_whatsapp||"",emergency_contact:r.emergency_contact||"",normal_class_time:r.preferred_class_time,email:r.parent_email,registration_date:new Date().toISOString().slice(0,10),active:true,commitment_confirmed:"No"});if(studentError)throw studentError;
 if(r.registration_type==="new_parent"){const{error}=await admin.from("parent_accounts").insert({user_id:r.parent_user_id,parent_name:r.parent_name,email:r.parent_email,whatsapp:r.parent_whatsapp||"",active:true,must_change_password:false});if(error){await admin.from("students").delete().eq("student_id",studentId);throw error;}}
 const{error:linkError}=await admin.from("parent_students").insert({parent_user_id:r.parent_user_id,student_id:studentId});if(linkError){await admin.from("students").delete().eq("student_id",studentId);if(r.registration_type==="new_parent")await admin.from("parent_accounts").delete().eq("user_id",r.parent_user_id);throw linkError;}
 const{error:updateError}=await admin.from("student_registrations").update({status:"Approved",student_id:studentId,reviewed_at:new Date().toISOString(),reviewed_by:u.user.id,rejection_reason:null}).eq("registration_id",id).eq("status","Pending Review");if(updateError)throw updateError;await sendMail(r.parent_email,"Banting Scrabble Academy Registration Approved",`<div style="font-family:Arial,sans-serif"><h2>Registration Approved</h2><p>Dear ${r.parent_name},</p><p>Your registration for <strong>${r.student_name}</strong> has been approved.</p><p>Student ID: <strong>${studentId}</strong></p><p>You can now sign in to the Parent Portal.</p></div>`);return json({success:true,status:"Approved",student_id:studentId});
 }catch(error){console.error("review-student-registration error",error);return json({error:error instanceof Error?error.message:"Unable to process the registration."},500);}});
